Update PM2 process name in deployment workflow for consistency
Changed the PM2 process name from 'crowd-admin' to 'crowdadmin' in the GitHub Actions deployment workflow. This update ensures consistency in process naming and improves the reliability of the deployment script.

diff --git a/.github/workflows/admin.yml b/.github/workflows/admin.yml
--- a/.github/workflows/admin.yml
+++ b/.github/workflows/admin.yml
@@ -49,8 +49,8 @@ jobs:
             ls -la dist/
 
             echo "Restarting PM2 service..."
-            pm2 delete crowd-admin || echo "No existing PM2 process found"
-            NODE_NO_WARNINGS=1 pm2 start http-server --name crowd-admin -- /var/www/crowd/admin/dist -p 8210 --cors || { echo "PM2 start failed"; exit 1; }
+            pm2 delete crowdadmin  || echo "No existing PM2 process found"
+            NODE_NO_WARNINGS=1 pm2 start http-server --name crowdadmin  -- /var/www/crowd/admin/dist -p 8210 --cors || { echo "PM2 start failed"; exit 1; }
             pm2 save || { echo "PM2 save failed"; exit 1; }
 
             echo "Deployment completed successfully"
